# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MemberManagement' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MemberManagement
  pod 'Alamofire'
end

target 'SampleiOS.181121' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleiOS.181121

end
